imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_base_urls: http://www.thegabrielhotel.com/gabrielnew/gabriel-final/web
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        name: gabriel_session
        cookie_httponly: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:  http://www.thegabrielhotel.com/gabrielnew/gabriel-final/web
    bundles:        [ GbrFEBundle, GbrBEBundle, FOSUserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: [ GbrFEBundle, GbrBEBundle, FOSUserBundle ]
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

#Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

#doctrine_mongodb:
#    connections:
#        default:
#            server: %database_server%
#            options: {}
#    default_database: %database_name%
#    document_managers:
#        default:
#            auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
#    host:      ~
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%
    encryption: %mailer_enc%
#    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Gbr\BEBundle\Entity\User
    from_email:
        address:        system@thegabrielhotel.com
        sender_name:    Gabriel hotel admin password resetting
    service:
        mailer: fos_user.mailer.default